title: "My Blog."
author: "Paweł Habrzyk"
description: "My blog. Enjoy."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://habrzyk-pawel.github.io"

# Build settings
enforce_https: true
